= Adjusting timeouts and resources

When a Release Pipeline is executed through a PipelineRun, the Pipeline will run until a timeout is reached. This timeout is usually an hour and will make the Release Pipeline fail if it doesn't finish on time.

To overcome this, there are two strategies {ProductName} users can follow.

== Adjust timeouts

Whenever a pipeline is defined through the xref:release-service-reference.adoc#releaseplan_spec[pipelineRef field in the ReleasePlan] or the xref:release-service-reference.adoc#releaseplanadmission_spec[pipelineRef field in the ReleasePlanAdmission], users can specify a `timeout` field in the following way:

[source,yaml]
----
pipelineRef:
  resolver: git
  params:
    - name: url
      value: "<url-to-repo>.git"
    - name: revision
      value: main
    - name: pathInRepo
      value: "<path-to-your-pipeline>"
  timeout: "2h0m0s" <.>
----

<.> Specifies the timeout for the entire PipelineRun. Defaults to the global configurable default timeout of 60 minutes.

With the new API, the `timeout` field in `ReleasePlanAdmission` has been moved and expanded into `pipeline.timeouts` to allow for more granular control over task and finally timeouts.

[source,yaml]
----
spec:
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "<url-to-repo>.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "<path-to-your-pipeline>"
      resolver: git
    serviceAccountName: release-service-account
    timeouts:
      finally: "15m0s" <.>
      pipeline: "2h0m0s" <.>
      tasks: "1h30m0s" <.>
----
<.> Specifies the maximum allowed duration for the `finally` section of the pipeline.
<.> Specifies the maximum allowed duration for the execution of the entire pipeline. The sum of individual timeouts for tasks and finally must not exceed this value.
<.> Specifies the maximum allowed duration for the pipeline's tasks.

== Adjust resources

As can be seen in the section above, there's no way to specify timeouts for individual tasks. However, another field can be used to increase the resources an specific task can use during its execution.

*Giving additional recourses to the verify-enterprise-contract task*

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/block-releases: 'false'
  name: sre-production
  namespace: managed-tenant-namespace
spec:
  applications:
    - demo-app
  origin: <dev-tenant-namespace>
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "<url-to-repo>.git"
        - name: revision
          value: main
        - name: pathInRepo
          value: "<path-to-your-pipeline>"
      resolver: git
    serviceAccountName: release-service-account <.>
    timeouts:
      pipeline: "2h0m0s"
  policy: <policy>
----

<.> Name of the service account to use in the Release PipelineRun to gain elevated privileges. This field has been moved from the top-level `spec` to `spec.pipeline`.