= Adjusting timeouts and resources

When a Release Pipeline is executed through a PipelineRun, the Pipeline will run until a timeout is reached. This timeout is usually an hour and will make the Release Pipeline fail if it doesn't finish on time.

To overcome this, there are two strategies {ProductName} users can follow.

== Adjust timeouts

Whenever a pipeline is defined through the xref:release-service-reference.adoc#releaseplan_spec[pipelineRef field in the ReleasePlan] or the xref:release-service-reference.adoc#releaseplanadmission_spec[pipelineRef field in the ReleasePlanAdmission], users can specify a `timeout` field in the following way:

[source,yaml]
----
pipelineRef:
  resolver: git
  params:
    - name: url
      value: "<url-to-repo>.git"
    - name: revision
      value: main
    - name: pathInRepo
      value: "<path-to-your-pipeline>"
  timeout: "2h0m0s" <.>
----

<.> Specifies the timeout for the entire PipelineRun. Defaults to the global configurable default timeout of 60 minutes.

== Adjust resources

As can be seen in the section above, there's no way to specify timeouts for individual tasks. However, another field can be used to increase the resources an specific task can use during its execution.

*Giving additional recourses to the verify-enterprise-contract task*

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
  name: sre-production
  namespace: managed-tenant-namespace
spec:
  applications:
    - demo-app
  origin: <dev-tenant-namespace>
  pipelineRef:
    params:
      - name: url
        value: "<url-to-repo>.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "<path-to-your-pipeline>"
    resolver: git
    timeout: "2h0m0s"
  policy: <policy>
  serviceAccount: release-service-account <.>
----

<.> Name of the Task we want to modify.