= Creating a release

A Release CR is created to submit a specific Application Snapshot to be processed according to the referenced ReleasePlan.

== Creating a `Release` object

The development team creates a `Release` object in the developer tenant namespace. The `Release` object includes a reference to the application snapshot that the development team wants to release, along with release plan that will be used to release the application.

. The `Release` object can also contain additional data or specify a custom timeout for the release pipeline.

.*Prerequisites*

* You have an existing Development tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* You have completed the steps for creating a ReleasePlanAdmission and a matching ReleasePlan.

.*Procedures*

. Create a `Release.yaml` object locally.

+
*Example `Release.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: <name-of-this-release> <.>
  namespace: dev-tenant-namespace <.>
spec:
  releasePlan: <release-plan-name> <.>
  snapshot: <application-snapshot-name> <.>
  target: <.>
    namespace: <target-namespace-for-release> <.>
    workspace: <target-workspace-for-release> <.>
----

+
<.> The name of the release.
<.> The development team's tenant namespace.
<.> The name of the release plan specifying the pipeline to run.
<.> The name of the application snapshot that you want to release.
<.> The target for this release. This field indicates where the release is intended to be released.
<.> The target namespace within the cluster where the release is intended to be released.
<.> The target KCP workspace within the cluster where the release is intended to be released.

. In the development tenant namespace, apply the `Release.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
$ kubectl apply -f Release.yaml -n dev
----

.*Verification*

. In the {ProductName} UI, select the *Applications* tab
. Click on the application that is being released
. Click on the *Releases* tab
. See the recent releases that have been created for the application.
. You can find a link to the release pipeline run by clicking on the name of the release that you created.