= Creating a release

A `Release` object informs Konflux that an Application's
xref:testing:page$integration/snapshots/index.adoc[Snapshot] is ready to be released, in accordiance
with its associated xref:create-release-plan.adoc[ReleasePlan].

== Creating a `Release` object

The development team creates a `Release` object in the developer tenant namespace. The `Release` object includes a reference to the application component snapshot that the development team wants to release, along with release plan that will be used to release the application.

. The `Release` object can also contain additional data or specify a custom timeout for the release pipeline.

*Prerequisites*

* You have an existing Development tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* You have completed the steps for creating a ReleasePlanAdmission and a matching ReleasePlan.

*Procedures*

. Create a `Release.yaml` object locally.

+
include::releasing:partial$example-manual-release.adoc[]

. In the development tenant namespace, create the `Release` object using the `kubectl` command line:
+
[source,shell]
----

. Remove the following fields from the `Release.yaml` object:
.. `metadata` fields:
... `annotations`
... `creationTimestamp`
... `finalizers`
... `generation`
... `name`
... `ownerReferences`
... `resourceVersion`
... `uid`
.. `status` - remove entirely or set its value to `{}`

. Verify that the `Release.yaml` object is valid:
+
include::releasing:partial$example-manual-release.adoc[]

. Create the new `Release` object using the data in `Release.yaml`:
+
[source,shell]
----
$ kubectl create -f Release.yaml
----

*Verification*

. In the {ProductName} UI, select the *Applications* tab
