= Creating a release plan admission

A ReleasePlanAdmission (RPA) CR exists within a managed tenant namespace. It defines the specific pipeline to run and a given xref:compliance:index.adoc[Conforma] Policy which needs to pass for the Snapshot before that pipeline can proceed.

When an application is ready for release, the Development team contacts the owners of the managed tenant namespace (for example, their organization's SRE team) and requests access to the managed tenant namespace. A RPA object is then created in the managed tenant namespace to specify the configuration.

== Creating a `ReleasePlanAdmission` object

.*Prerequisites*

* An existing Development and Managed tenant namespace.
* You have completed the steps listed in the xref:ROOT:getting-started.adoc#getting-started-with-the-cli[Getting started in the CLI] page.
* An existing `ReleasePlan` object in the Development tenant namespace.

.*Procedures*

. Create a `ReleasePlanAdmission.yaml` object locally.

+
*Example `ReleasePlanAdmission.yaml` object*

+
[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  creationTimestamp: null
  labels:
    release.appstudio.openshift.io/auto-release: 'true' <.>
  name: sre-production <.>
  namespace: managed-tenant-namespace <.>
spec:
  applications:
  - demo-app <.>
  approvalMode: <approval-mode> <.>
  autoRelease: <auto-release> <.>
  data: {} <.>
  environment: <sre-production> <.>
  notificationConfig: <notification-config> <.>
  origin: <dev-tenant-namespace> <.>
  pipelineRef:
    params: <params> <.>
    resolver: <resolver> <.>
    timeout: <timeout> <.>
  policy: <policy> <.>
  serviceAccount: <service-account> <.>
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
----

+
<.> Optional: Control whether or not this ReleasePlanAdmission is entirely disabled. If set to false, attempted releases will fail with a validation error. Defaults to true.
<.> The name of the release plan admission.
<.> The Managed environment team's tenant namespace.
<.> A list of applications that you want to enable to be deployed in the managed tenant namespace.
<.> Defines the approval process for releases. Possible values are `manual`, `automatic`, or `policy-based`.
<.> Optional: When set to `true`, enables automatic release creation when conditions are met.
<.> Optional: Unstructured key for providing data for the release Pipeline.
<.> Optional: The environment from which the application updates are allowed to be received in the Managed tenant namespace. This environment is created by the Development team.
<.> Optional: Defines notification settings for release events. It has subfields: `channels` (list of notification channels like `slack`, `email`) and `events` (list of events like `release-started`, `release-completed`, `release-failed`, `approval-required`).
<.> The development team tenant namespace where the application is defined.
<.> Parameters for the referenced pipeline.
<.> Name of a Tekton resolver to be used (for example, `git`).
<.> Optional: Timeout value to override the Tekton default PipelineRun timeout. Defaults to "0", which means no timeout.
<.> The enterprise contract policy against which the system validates an application before releasing it to production.
<.> Optional: The name of the service account to use in the release PipelineRun to gain elevated privileges. It's used only if you have defined the `pipelineRef` value.

+
NOTE: The ReleasePlanAdmission.yaml represents the reciprocal link to the ReleasePlan.yaml objects created by the development team.

. In the Managed tenant namespace, apply the `ReleasePlanAdmission.yaml` file and add the resource to your cluster by running the following command:

+
[source,shell]
----
kubectl apply -f ReleasePlanAdmission.yaml -n managed
----

.*Verification*

. In the {ProductName} UI, select the *Release services* > *Release plan admission* tab.
. Review the RPA object that you just added. Using the Release plan admission tab, you can update or delete the selected Release plan admission object.
. When a ReleasePlanAdmission is correctly configured to be paired with a ReleasePlan, its *Status* will display as being `Active`.