= Release Pipelines

The release process with {ProductName} is well-structured, and the documentation provides clear examples of how to supply data to the `Release`, `ReleasePlan`, or `ReleasePlanAdmission` resources for use within the release workflow.

To address a previous limitation where data fields needed to be populated with dynamic information, {ProductName} now supports release pipelines. Release pipelines are responsible for running the tasks required to validate, collect, and release information. These pipelines are integrated into the release workflow and run at the very beginning, immediately after the validation step. As a result, the collected data becomes available to both the _tenant_ and _managed_ pipelines.

== Using release pipelines in a {ProductName} release

To use a release pipeline, the first step is to select one from the available options in https://github.com/konflux-ci/release-service-catalog/tree/main/pipelines[the official repository]. The structure of this repository may evolve over time, but the https://github.com/konflux-ci/release-service-catalog/blob/main/pipelines/README.md[README.md] file provides useful details about the available pipelines and the data they produce. The key piece of information needed is the pipeline's name, which will be referenced in one of the release resources.

Release pipelines can be defined in the following resources:

* *ReleasePlan:* Pipelines defined here are executed by the _tenant pipeline_, which runs in the tenant namespace.
* *ReleasePlanAdmission:* Pipelines defined here are executed by the _managed pipeline_, which runs in the managed namespace.

For example, to run the `release` pipeline—which retrieves a list of Jira issues when provided with a server and a query—the following configuration should be added to the _ReleasePlan_:

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true' <.>
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: collectors-rp
  namespace: dev-tenant-namespace <.>
spec:
  application: <application-name> <.>
  displayName: "My Release Plan" <.>
  pipelineRef: <.>
    params:
      - name: SCRIPT_FILENAME
        value: collect-jira-issues
      - name: JIRA_SERVER
        value: https://issues.redhat.com
      - name: JIRA_QUERY
        value: project = CPAAS AND labels = release AND fixVersion in ("2.0.0", "2.1.0")
    resolver: git
    timeout: 30s
  releaseStrategy: rolling <.>
  target: managed-tenant-namespace
----
<.> Optional: Control if Releases should be created automatically for this ReleasePlan when tests pass. Defaults to true.
<.> The development team's tenant namespace. The collector pipeline will be executed in this namespace.
<.> The name of the application *component* that you want to release via a pipeline in the development tenant namespace.
<.> The user-friendly name of the ReleasePlan.
<.> The pipelineRef field replaces the previous collectors field and points to the pipeline to be executed to collect data.
<.> The release strategy to be applied, e.g., `rolling`, `blue-green`, `canary`, or `immediate`.

== Retrieving Release Pipeline data

After the release pipelines complete execution, the output from each pipeline is added to the `Release` resource under the `status.release` field. Below is an example showing the result of a pipeline defined in the previously mentioned _ReleasePlan_:

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
...
status:
  release:
    tenant:
      - project-issues:
          releaseNotes:
            fixed:
             - id: "CVE-3444"
               source: "issues.redhat.com"
----

In this case, the `project-issues` pipeline generated a list of issues, which is included under `status.release.tenant`. Since this pipeline was defined in the `ReleasePlan`, its output is categorized under the `tenant` section. Pipelines defined in a `ReleasePlanAdmission` will have their results stored under the `managed` key instead.

The following example shows a `Release` status containing results from multiple pipelines, both _tenant_ and _managed_:

[source,yaml]
----
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
...
status:
  release:
    managed:
      - foo:
          releaseNotes:
            cves:
             - key: "CVE-3444"
               component: "my-component"
    tenant:
      - bar:
          baz: qux
      - project-issues:
          releaseNotes:
            issues:
              fixed:
                - id: "CPAAS-1234"
                  source: "issues.redhat.com"
----

## Release data in the managed pipeline

Releases can reference _managed pipelines_, which—as described in other sections—rely on the `data` field to retrieve user-provided information. To ensure that data generated by _pipelines_ is also considered, the contents of `status.release` are merged with the data fields from the `Release`, `ReleasePlan`, and `ReleasePlanAdmission` resources.

The order of precedence follows the same hierarchy previously described, with `status.release` having the *lowest priority*. This means that if both the pipeline output and any data field define the same key, the value from the `data` field will take precedence.

For example, if a pipeline like `jira` produces the following output:

[source,yaml]
----
status:
  release:
    tenant:
      - project-issues:
          releaseNotes:
            issues:
              fixed:
                - id: "CPAAS-1234"
                  source: "issues.redhat.com"
          releaseNotes:
            cves:
             - key: "CVE-3444"
               component: "my-component"
----

And the `ReleasePlanAdmission` defines this:

[source,yaml]
----
data:
  releaseNotes:
    issues:
      fixed: []
----

Then the empty `issues.fixed` array from the `data` field will override the pipeline’s output.

In contrast, if the `data` field contains unrelated content:

[source,yaml]
----
data:
  foo: bar
----

Then both sources will be merged, and the final data used by the managed pipeline will be:

[source,yaml]
----
data:
  foo: bar
  releaseNotes:
    issues:
      fixed:
        - id: "CPAAS-1234"
          source: "issues.redhat.com"
----

This _merging strategy_ ensures flexibility while allowing user-defined data to take precedence when needed.